AWSTemplateFormatVersion: 2010-09-09
Description: Creating Amazon S3 bucket from CloudFormation

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: i-named-this-bucket
      VersioningConfiguration:
        Status: Enabled
  Outputs:
    S3Bucket:
      Description: Bucket created using this template
      Value: !Ref S3Bucket